### ISSUE TITLE
Video codec not found

### ISSUE THREAD

**Issue by petersondrew** [nixxquality/FFMSSharp#12]
When FFMS reports FFMS_ERROR_CODEC, FFMSSharp throws a NotImplementedException.
It would be nice if there was a specific exception type for this.

**Comment by nixxquality** [comment]
Sorry for the slow response. I am working on this, as well as bringing FFMS# up to date with other API changes.

**Comment by nixxquality** [comment]
You will now be able to update to FFMS# 3.0 via NuGet or you can compile it manually from the new home at https://gitgud.io/nixx/FFMSSharp

Please note that there are some breaking changes, and as such it's 3.0 and not 2.1

Audio tracks are no longer indexed by default and there are some new Indexer. functions you can use.
